### ISSUE TITLE
Allow damping=0

### ISSUE THREAD

**Issue by jamesplease** [skevy/wobble#39]
When damping is set to 0 a spring oscillates indefinitely. Presently, wobble [errors when `damping` is 0](https://github.com/skevy/wobble/blob/2678d7d0f3605ee447c8c1ac4b69eef7b2cd88cf/src/index.ts#L292).  Perhaps the motivation here is that for many use cases this behavior is unintentional (i.e.; many web apps that use spring motion likely want the value to come to rest).

However, there are plenty of situations where neverending oscillation is desired. One example that comes to mind is games.

Would you be open to a change that allows damping to be set to 0?

If you're particularly worried about unintentional infinite oscillations, one solution to this problem would be to add a new option, perhaps it could be called `allowZeroDamping` or `allowInfiniteOscillation`. When set to `false`, the current error is still thrown when `damping` is 0. When `true`, no error is thrown. The default value could be `false` for backwards compatibility. Personally, I think it'd be fine to just remove the error altogether , as other popular spring libraries allow infinite oscillations without an explicit opt in.

Whaddaya say?

**Comment by skevy** [comment]
Closed in #40
